issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/images-bite-back-talk:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/images-bite-back-talk/.github/workflows/digestabot.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
